import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		ObjectInputStream input = new ObjectInputStream(s.getInputStream());
		Key key_final = (Key) input.readObject(); 

		// -Use the key to decrypt the incoming message from socket s.
	
		//https://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html

		Cipher c = Cipher.getInstance("DES/ECB/PKCS5Padding");
		c.init(Cipher.DECRYPT_MODE, key_final);
		CipherInputStream cstream= new CipherInputStream(s.getInputStream(),c);	
		// -Print out the decrypt String to see if it matches the original message.
		//also need to convert to string
		
		int decrypted = cstream.read();
		StringBuilder decryp_text = new StringBuilder();
		//int length = String.valueOf(decrypted).length();
		//for (int i = 0; i<length; i++) doesn't work, EOF error
		while( decrypted  != -1){
			//convert to character
			decryp_text.append((char) decrypted);

			
		decrypted = cstream.read();
		
			}
		System.out.println("Decrypted Message: " );
		System.out.println(decryp_text.toString());
		input.close();
		cstream.close();
		server.close();
		
	}
}